<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>New Page 1</title>
<base target="contents">
</head>
<body bgcolor="ivory" margin=0 topmargin="0" leftmargin="0">
  <table border="0" width="800" height="86" cellspacing="0" cellpadding="0" bgcolor="ivory">
    <tr>
      <td width="186" height="62">　</td>
      <td width="347" height="62">
      </td>
    </tr>
    <tr>
      <td width="190" height="16">&nbsp;&nbsp;&nbsp; </td>
      <td width="186" height="16"></td>
      <td width="247" height="16"></td>
    </tr>
    <tr>
      <td width="190" height="16"></td>
      <td width="186" height="16"></td>
      <td width="247" height="16"></td>
    </tr>
  </table>
</body>

</html>
